import { Inter } from '@next/font/google'
import Head from 'next/head'
import Homepage from "../components/Homepage"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>F$savings - Let us handle your finances</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Homepage />
      </>
  )
}
